TARGET = libhpss.so

SRCS = libhpss.cpp

HEADERS = 

EXTRALIBS = -lhpss \
            -lhpsscs \
            -lhpsskrb5auth \
            -lhpssunixauth \
            -lboost_filesystem

include ../Makefile.base
